version: '3.8'

services:
  # 1. Layanan Database (PostgreSQL)
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fullstack_challenge
    ports:
      - '5432:5432' # Hanya untuk debugging lokal
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Layanan Caching (Redis)
  cache:
    image: redis:7-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379' # Hanya untuk debugging lokal

  # 3. Layanan Message Broker (RabbitMQ)
  broker:
    image: rabbitmq:3-management-alpine
    container_name: broker
    restart: always
    ports:
      - '5672:5672'  # Port AMQP
      - '15672:15672' # UI Manajemen RabbitMQ
    
    # === PERBAIKAN 1: TAMBAHKAN HEALTHCHECK ===
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s

  # 4. Layanan Produk (NestJS)
  product-service:
    container_name: product-service
    # 'build:' menunjuk ke folder tempat Dockerfile NestJS berada
    build:
      context: ../challenge-product-service
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Port NestJS

    # === PERBAIKAN 2: GUNAKAN CONDITIONAL DEPENDENCY ===
    depends_on:
      db:
        condition: service_started
      cache:
        condition: service_started
      broker:
        condition: service_healthy # Menunggu broker siap sebelum memulai product-service

    environment:
      DATABASE_URL: 'postgresql://admin:admin@db:5432/fullstack_challenge'
      REDIS_HOST: 'cache'
      REDIS_PORT: 6379
      RABBITMQ_URL: 'amqp://guest:guest@broker:5672'

  # 5. Layanan Order (Go)
  order-service:
    container_name: order-service
    # 'build:' menunjuk ke direktori saat ini (repo Go)
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # Port Go

    # === PERBAIKAN 3: GUNAKAN CONDITIONAL DEPENDENCY (untuk konsistensi) ===
    depends_on:
      db:
        condition: service_started
      cache:
        condition: service_started
      broker:
        condition: service_healthy # Menunggu broker siap sebelum memulai order-service

    environment:
      DATABASE_URL: 'postgresql://admin:admin@db:5432/fullstack_challenge'
      REDIS_HOST: 'cache'
      REDIS_PORT: 6379
      RABBITMQ_URL: 'amqp://guest:guest@broker:5672'
      PRODUCT_SERVICE_URL: 'http://product-service:3000' # Untuk memanggil API NestJS

# Volume untuk menyimpan data Postgres
volumes:
  postgres_data: